language: python
sudo: required
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

env:
  - NEO4J_VERSION="3.5.24"
  - NEO4J_VERSION="4.0.9"
  - NEO4J_VERSION="4.1.4"
  - NEO4J_VERSION="4.2.0"
before_install:
  - sudo add-apt-repository -y ppa:openjdk-r/ppa
  - sudo apt-get update && sudo apt-get install openjdk-11-jre-headless
  - curl -L http://dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz | tar xz
install: "python setup.py install"
before_script:
  - neo4j-community-$NEO4J_VERSION/bin/neo4j-admin set-initial-password foobar
  - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 neo4j-community-$NEO4J_VERSION/bin/neo4j start
  - export DJANGO_SETTINGS_MODULE=settings
  - sleep 10
script:
  - cd tests
  - ./manage.py install_labels
  - ./manage.py migrate
  - export DJANGO_SETTINGS_MODULE=tests.settings
  - pytest
